
version: '3.0'

services:
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  producer: 
    build: producer
    links:
      - rabbitmq
    volumes:
      - ./producer:/producer
    ports:
      - '127.0.0.1:5000:5000'

  consumer:
    # restart: always
    build: consumer
    links:
      - rabbitmq
    volumes:
      - ./consumer:/consumer
    environment:
      - SERVER_IP=producer
      - SERVER_PORT=5000
      - CUST_ID=1
    
  database:
    # restart: always
    build: database
    links:
      - mongodb
      - rabbitmq
    volumes:
     - ./database:/database
    
  mongodb:
    image: mongo
    ports:
      - 27017


