
version: '3.8'

services:
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - custom_network

  consumer:
    build: consumer
    volumes:
      - ./consumer:/consumer
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCERIP=127.0.0.1
      - PRODUCERPORT=5000
    networks:
      - custom_network

  database:
    build: database
    volumes:
     - ./database:/database
    networks:
      - custom_network

  server:
    build: producer
    volumes:
      - ./producer:/producer
    ports:
      - 5000:5000
    networks:
      - custom_network

networks:
  custom_network:
    driver: custom-driver-1