
version: '3.0'

services:
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  producer: 
    restart: always
    build: producer
    volumes:
      - ./producer:/producer
    ports:
      - '5000:5000'

  consumer:
    restart: always
    build: consumer
    volumes:
      - ./consumer:/consumer
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCERIP=127.0.0.1
      - PRODUCERPORT=5000
    
  database:
    restart: always
    build: database
    volumes:
     - ./database:/database
    
    


